require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/journal_entries", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # JournalEntry. As you add validations to JournalEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # JournalEntriesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      JournalEntry.create! valid_attributes
      get journal_entries_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      journal_entry = JournalEntry.create! valid_attributes
      get journal_entry_url(journal_entry), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JournalEntry" do
        expect {
          post journal_entries_url,
               params: { journal_entry: valid_attributes }, headers: valid_headers, as: :json
        }.to change(JournalEntry, :count).by(1)
      end

      it "renders a JSON response with the new journal_entry" do
        post journal_entries_url,
             params: { journal_entry: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JournalEntry" do
        expect {
          post journal_entries_url,
               params: { journal_entry: invalid_attributes }, as: :json
        }.to change(JournalEntry, :count).by(0)
      end

      it "renders a JSON response with errors for the new journal_entry" do
        post journal_entries_url,
             params: { journal_entry: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry),
              params: { journal_entry: new_attributes }, headers: valid_headers, as: :json
        journal_entry.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry),
              params: { journal_entry: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry),
              params: { journal_entry: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested journal_entry" do
      journal_entry = JournalEntry.create! valid_attributes
      expect {
        delete journal_entry_url(journal_entry), headers: valid_headers, as: :json
      }.to change(JournalEntry, :count).by(-1)
    end
  end
end
